# This file was generated by GoReleaser. DO NOT EDIT.
cask "apig-swagger-ui" do
  version "1.6.7"

  on_macos do
    on_intel do
      url "https://github.com/james-hu/apig-swagger-ui/releases/download/v#{version}/apig-swagger-ui_#{version}_darwin_amd64.tar.gz"
      sha256 "a7e68563eb5840181377002288dd0c783ddb84f8ea9a7c3c57d9182fe7496c13"
    end
    on_arm do
      url "https://github.com/james-hu/apig-swagger-ui/releases/download/v#{version}/apig-swagger-ui_#{version}_darwin_arm64.tar.gz"
      sha256 "ae9110e5dcf130452e8567af5b8a1a05dd82ce9d14c3a9e6a9fbc1f7e8ace180"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/james-hu/apig-swagger-ui/releases/download/v#{version}/apig-swagger-ui_#{version}_linux_amd64.tar.gz"
      sha256 "64f519dfa2e3776f14bea1af2d1de7959e044a5d7828a52f3b34e5d44b995c4c"
    end
    on_arm do
      url "https://github.com/james-hu/apig-swagger-ui/releases/download/v#{version}/apig-swagger-ui_#{version}_linux_arm64.tar.gz"
      sha256 "a37df33eeb04f52c7b3900b48671c6fd90ac178b6aaed7c10e4efd39242cf88c"
    end
  end

  name "apig-swagger-ui"
  desc "Command line tool for generating OpenAPI spec and Swagger UI from AWS API Gateway"
  homepage "https://github.com/james-hu/apig-swagger-ui"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "apig-swagger-ui"

  # No zap stanza required

end
