# This file was generated by GoReleaser. DO NOT EDIT.
cask "apig-swagger-ui" do
  version "1.6.6"

  on_macos do
    on_intel do
      url "https://github.com/james-hu/apig-swagger-ui/releases/download/v#{version}/apig-swagger-ui_#{version}_darwin_amd64.tar.gz"
      sha256 "1396eca1ab2ed4de7b51f73e2774414b1927a8fc3fad7dcd12a438ad8ba19bd2"
    end
    on_arm do
      url "https://github.com/james-hu/apig-swagger-ui/releases/download/v#{version}/apig-swagger-ui_#{version}_darwin_arm64.tar.gz"
      sha256 "72a4427cfde8ac728d88333ea8c67f8cab173670a4239f0307f823f8fdf1b00c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/james-hu/apig-swagger-ui/releases/download/v#{version}/apig-swagger-ui_#{version}_linux_amd64.tar.gz"
      sha256 "d1e5173d319199211523f4486426f48327ea1ccca61e0977acfdcb3f3e65b16f"
    end
    on_arm do
      url "https://github.com/james-hu/apig-swagger-ui/releases/download/v#{version}/apig-swagger-ui_#{version}_linux_arm64.tar.gz"
      sha256 "dc28791b159f2992c739d23bf34941dcad2c1fd97f878e23742d6520caddd8cc"
    end
  end

  name "apig-swagger-ui"
  desc "Command line tool for generating OpenAPI spec and Swagger UI from AWS API Gateway"
  homepage "https://github.com/james-hu/apig-swagger-ui"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "apig-swagger-ui"

  # No zap stanza required

end
