# This file was generated by GoReleaser. DO NOT EDIT.
cask "apig-swagger-ui" do
  version "1.6.5"

  on_macos do
    on_intel do
      url "https://github.com/james-hu/apig-swagger-ui/releases/download/v#{version}/apig-swagger-ui_#{version}_darwin_amd64.tar.gz"
      sha256 "285d052545a0160daec76a801b82e8b08eb37f677a04f7af4e3c95fd4c4717e9"
    end
    on_arm do
      url "https://github.com/james-hu/apig-swagger-ui/releases/download/v#{version}/apig-swagger-ui_#{version}_darwin_arm64.tar.gz"
      sha256 "1394ed47110dca0686c86134025e58d2c69d04033b62558e34f5fe6992d0ac6c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/james-hu/apig-swagger-ui/releases/download/v#{version}/apig-swagger-ui_#{version}_linux_amd64.tar.gz"
      sha256 "1582a20f8fbec9c96c2cfffff1a0b41fbc9cbb1652d2109b59bad7ad2718d03f"
    end
    on_arm do
      url "https://github.com/james-hu/apig-swagger-ui/releases/download/v#{version}/apig-swagger-ui_#{version}_linux_arm64.tar.gz"
      sha256 "e11a3b6c46f24f2b553bea05b4f6e8778d80d2a59bd2f4fa9b26de745ec9b246"
    end
  end

  name "apig-swagger-ui"
  desc "Command line tool for generating OpenAPI spec and Swagger UI from AWS API Gateway"
  homepage "https://github.com/james-hu/apig-swagger-ui"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "apig-swagger-ui"

  # No zap stanza required

end
