# This file was generated by GoReleaser. DO NOT EDIT.
cask "aws-serverless-dataflow" do
  version "1.5.2"

  on_macos do
    on_intel do
      url "https://github.com/james-hu/aws-serverless-dataflow/releases/download/v#{version}/aws-serverless-dataflow_#{version}_darwin_amd64.tar.gz"
      sha256 "df6ba09df34096fafcd355d62e9a3133db8367c8ae7f190b37c25a3c6425253c"
    end
    on_arm do
      url "https://github.com/james-hu/aws-serverless-dataflow/releases/download/v#{version}/aws-serverless-dataflow_#{version}_darwin_arm64.tar.gz"
      sha256 "775bb9bac12f454a523aaac6dcd58835d6370fd778b11ecb2fb763a9c9aa9ea1"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/james-hu/aws-serverless-dataflow/releases/download/v#{version}/aws-serverless-dataflow_#{version}_linux_amd64.tar.gz"
      sha256 "e3de65b2a8af815e5a93d56ec6a73f66e92d6a43c2f1dce2c169c841cdb5f70d"
    end
    on_arm do
      url "https://github.com/james-hu/aws-serverless-dataflow/releases/download/v#{version}/aws-serverless-dataflow_#{version}_linux_arm64.tar.gz"
      sha256 "30379c66eb76ea952e40751bb1bfe9fe9da81f9db60a6196d742219bcf9737dc"
    end
  end

  name "aws-serverless-dataflow"
  desc "A command-line tool for visualisation of AWS serverless (Lambda, API Gateway, SNS, SQS, etc.) dataflow"
  homepage "https://github.com/james-hu/aws-serverless-dataflow"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "aws-serverless-dataflow"

  # No zap stanza required

end
