# This file was generated by GoReleaser. DO NOT EDIT.
cask "aws-serverless-dataflow" do
  version "1.5.1"

  on_macos do
    on_intel do
      url "https://github.com/james-hu/aws-serverless-dataflow/releases/download/v#{version}/aws-serverless-dataflow_#{version}_darwin_amd64.tar.gz"
      sha256 "b713c923f207ff992fe8654d812f3e002f53ca9899c49dfa99d1d894c4b9ac1a"
    end
    on_arm do
      url "https://github.com/james-hu/aws-serverless-dataflow/releases/download/v#{version}/aws-serverless-dataflow_#{version}_darwin_arm64.tar.gz"
      sha256 "64781f188d58a61cd597a973e13e5b837ad6b66279fbccc1af30f0f85fa03595"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/james-hu/aws-serverless-dataflow/releases/download/v#{version}/aws-serverless-dataflow_#{version}_linux_amd64.tar.gz"
      sha256 "034d202e187f579557fd02d614d690d21dd823b0dcb91c652ab6af8a420142fd"
    end
    on_arm do
      url "https://github.com/james-hu/aws-serverless-dataflow/releases/download/v#{version}/aws-serverless-dataflow_#{version}_linux_arm64.tar.gz"
      sha256 "2cce4b6d550be9cca17ecc225bcdf4ddfe541eda49e19a98bf33ecb5af05f58e"
    end
  end

  name "aws-serverless-dataflow"
  desc "A command-line tool for visualisation of AWS serverless (Lambda, API Gateway, SNS, SQS, etc.) dataflow"
  homepage "https://github.com/james-hu/aws-serverless-dataflow"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "aws-serverless-dataflow"

  # No zap stanza required

end
