# This file was generated by GoReleaser. DO NOT EDIT.
cask "aws-serverless-dataflow" do
  version "1.5.3"

  on_macos do
    on_intel do
      sha256 "37e9e2bcb0ae8a69039ba1877beee58854661de806327e2252b18592ed5f9aea"
      url "https://github.com/james-hu/aws-serverless-dataflow/releases/download/v#{version}/aws-serverless-dataflow_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "96cdd4dd4dab62e8a9dd08f2fe71a33ac939ecd9af4b014de9c407e0d00c04c8"
      url "https://github.com/james-hu/aws-serverless-dataflow/releases/download/v#{version}/aws-serverless-dataflow_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "f770edcace1572d9ffbc704b5642ae92c45b1854b13a550dedded8f7105d10eb"
      url "https://github.com/james-hu/aws-serverless-dataflow/releases/download/v#{version}/aws-serverless-dataflow_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "4947984695ee005d74d9d0e1e52bbcae724d719beb4f5a191e6cd50578d7793c"
      url "https://github.com/james-hu/aws-serverless-dataflow/releases/download/v#{version}/aws-serverless-dataflow_#{version}_linux_arm64.tar.gz"
    end
  end

  name "aws-serverless-dataflow"
  desc "A command-line tool for visualisation of AWS serverless (Lambda, API Gateway, SNS, SQS, etc.) dataflow"
  homepage "https://github.com/james-hu/aws-serverless-dataflow"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "aws-serverless-dataflow"

  # No zap stanza required

end
