# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ApigSwaggerUi < Formula
  desc "Command line tool for generating OpenAPI spec and Swagger UI from AWS API Gateway"
  homepage "https://github.com/james-hu/apig-swagger-ui"
  version "1.4.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/james-hu/apig-swagger-ui/releases/download/v1.4.0/apig-swagger-ui_1.4.0_darwin_arm64.tar.gz"
      sha256 "92a89c609b652bacc0ba3e0f9daaca53f763cda950893006eeaf2d31ee627978"

      def install
        bin.install "apig-swagger-ui"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/james-hu/apig-swagger-ui/releases/download/v1.4.0/apig-swagger-ui_1.4.0_darwin_amd64.tar.gz"
      sha256 "52b88357171969e6b12837959700326640750a09347e2b41115bf71077410f21"

      def install
        bin.install "apig-swagger-ui"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/james-hu/apig-swagger-ui/releases/download/v1.4.0/apig-swagger-ui_1.4.0_linux_arm64.tar.gz"
      sha256 "7e97c2e54dd16bf1f62d17912f443aec3c7b1a9b8c9435d6e5b236f5db0ef579"

      def install
        bin.install "apig-swagger-ui"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/james-hu/apig-swagger-ui/releases/download/v1.4.0/apig-swagger-ui_1.4.0_linux_amd64.tar.gz"
      sha256 "627aa567835f317dd6a0271a7ef95b69dc9d5ca8152e4e1bb9ad992271372044"

      def install
        bin.install "apig-swagger-ui"
      end
    end
  end
end
