# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ApigSwaggerUi < Formula
  desc "Command line tool for generating OpenAPI spec and Swagger UI from AWS API Gateway"
  homepage "https://github.com/james-hu/apig-swagger-ui"
  version "1.2.4"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/james-hu/apig-swagger-ui/releases/download/v1.2.4/apig-swagger-ui_1.2.4_darwin_arm64.tar.gz"
      sha256 "ca44501dc8d15571682f4e9e3ae897b9c5ad3e09a45c10c404b42fc920b63d42"

      def install
        bin.install "apig-swagger-ui"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/james-hu/apig-swagger-ui/releases/download/v1.2.4/apig-swagger-ui_1.2.4_darwin_amd64.tar.gz"
      sha256 "4d0ef1dd9a04b91485457edbd58871b21a2e5980bddb3f2e8d02aff87f572a83"

      def install
        bin.install "apig-swagger-ui"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/james-hu/apig-swagger-ui/releases/download/v1.2.4/apig-swagger-ui_1.2.4_linux_arm64.tar.gz"
      sha256 "e81dc2c1341738dbcd5686d0a9e6e9eeea63303b07d22294e5f59d9893676140"

      def install
        bin.install "apig-swagger-ui"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/james-hu/apig-swagger-ui/releases/download/v1.2.4/apig-swagger-ui_1.2.4_linux_amd64.tar.gz"
      sha256 "1ca5ceb6668f44f1f142dba2ea7365a0980d7ccf2c1fba68a371e0cb8b958c3d"

      def install
        bin.install "apig-swagger-ui"
      end
    end
  end
end
