# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AwsServerlessDataflow < Formula
  desc "A command-line tool for visualisation of AWS serverless (Lambda, API Gateway, SNS, SQS, etc.) dataflow"
  homepage "https://github.com/james-hu/aws-serverless-dataflow"
  version "1.4.3"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/james-hu/aws-serverless-dataflow/releases/download/v1.4.3/aws-serverless-dataflow_1.4.3_darwin_arm64.tar.gz"
      sha256 "fe3274e937e2bc864ff43ccf087a05ea840630b166581c9b2f62d4992a6e2412"

      def install
        bin.install "aws-serverless-dataflow"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/james-hu/aws-serverless-dataflow/releases/download/v1.4.3/aws-serverless-dataflow_1.4.3_darwin_amd64.tar.gz"
      sha256 "fc843cd4253b418ee29202934b363c8785aef6a1a169a47e572425d09ee53fdb"

      def install
        bin.install "aws-serverless-dataflow"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/james-hu/aws-serverless-dataflow/releases/download/v1.4.3/aws-serverless-dataflow_1.4.3_linux_amd64.tar.gz"
      sha256 "d2647af79ada1e2bfc6d819f06bb1d35c88f43568d0801275a0b1320d828a2fc"

      def install
        bin.install "aws-serverless-dataflow"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/james-hu/aws-serverless-dataflow/releases/download/v1.4.3/aws-serverless-dataflow_1.4.3_linux_arm64.tar.gz"
      sha256 "13f4dc413943b917b6c8818ab9664f1bc6369474b7abb87f8e572db3b0627a5d"

      def install
        bin.install "aws-serverless-dataflow"
      end
    end
  end
end
