# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AwsServerlessDataflow < Formula
  desc "A command-line tool for visualisation of AWS serverless (Lambda, API Gateway, SNS, SQS, etc.) dataflow"
  homepage "https://github.com/james-hu/aws-serverless-dataflow"
  version "1.3.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/james-hu/aws-serverless-dataflow/releases/download/v1.3.1/aws-serverless-dataflow_1.3.1_darwin_arm64.tar.gz"
      sha256 "c98c69161b1fa2a321e1d464b3ebd91858fc7060d4b9f057db804b582462d50b"

      def install
        bin.install "aws-serverless-dataflow"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/james-hu/aws-serverless-dataflow/releases/download/v1.3.1/aws-serverless-dataflow_1.3.1_darwin_amd64.tar.gz"
      sha256 "16805cf1ab31f3cf04763b94c70cf34129a0ff415e40bdb9edc7ef383dba674b"

      def install
        bin.install "aws-serverless-dataflow"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/james-hu/aws-serverless-dataflow/releases/download/v1.3.1/aws-serverless-dataflow_1.3.1_linux_amd64.tar.gz"
      sha256 "c63894dcb1a3ce9513abb75f28a0f3cb42452fd8abbc0161bbfb9dba09b143ab"

      def install
        bin.install "aws-serverless-dataflow"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/james-hu/aws-serverless-dataflow/releases/download/v1.3.1/aws-serverless-dataflow_1.3.1_linux_arm64.tar.gz"
      sha256 "a5976b7e88b4e2ae86c127e03b6294c45d996cb76d94c965bdae7474d2963a7f"

      def install
        bin.install "aws-serverless-dataflow"
      end
    end
  end
end
