# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AwsServerlessDataflow < Formula
  desc "A command-line tool for visualisation of AWS serverless (Lambda, API Gateway, SNS, SQS, etc.) dataflow"
  homepage "https://github.com/james-hu/aws-serverless-dataflow"
  version "1.3.5"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/james-hu/aws-serverless-dataflow/releases/download/v1.3.5/aws-serverless-dataflow_1.3.5_darwin_arm64.tar.gz"
      sha256 "b3b220f43615580c2b731f39a607d7aee4849a5ad52500b2335bffc528639156"

      def install
        bin.install "aws-serverless-dataflow"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/james-hu/aws-serverless-dataflow/releases/download/v1.3.5/aws-serverless-dataflow_1.3.5_darwin_amd64.tar.gz"
      sha256 "35cc3cbcf9998f09767957489e7f0c793dda3b27f8e38b2515f2ee32381b625d"

      def install
        bin.install "aws-serverless-dataflow"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/james-hu/aws-serverless-dataflow/releases/download/v1.3.5/aws-serverless-dataflow_1.3.5_linux_arm64.tar.gz"
      sha256 "601f92d7fab9650276628ad02842e295feba6a2d6610184fceebd2d901ba6659"

      def install
        bin.install "aws-serverless-dataflow"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/james-hu/aws-serverless-dataflow/releases/download/v1.3.5/aws-serverless-dataflow_1.3.5_linux_amd64.tar.gz"
      sha256 "23a0ac570fd48557f9411e1b8029dc4799a4f2c69db0344512c4ddb2dba6de62"

      def install
        bin.install "aws-serverless-dataflow"
      end
    end
  end
end
