# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LsHaving < Formula
  desc "Command 'ls-having' can list directories having specified flag files and optionally meeting other specified conditions."
  homepage "https://github.com/handy-common-utils/ls-having"
  version "0.0.7"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/handy-common-utils/ls-having/releases/download/0.0.7/ls-having_0.0.7_Darwin_x86_64.tar.gz"
      sha256 "3cdb7d59c714018702cb3865ae0990356eb4472dbeeab04f80347219623ac2b2"

      def install
        bin.install "ls-having"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/handy-common-utils/ls-having/releases/download/0.0.7/ls-having_0.0.7_Darwin_arm64.tar.gz"
      sha256 "2ff84d2caa57852d3d40a22e75fa267570186b4f0aef72fd8c0cc524bc93a0a5"

      def install
        bin.install "ls-having"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/handy-common-utils/ls-having/releases/download/0.0.7/ls-having_0.0.7_Linux_arm64.tar.gz"
      sha256 "680fa707a06c2dd43280e34b8e944bc167c1efc5bf92f4394963a5c46144546f"

      def install
        bin.install "ls-having"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/handy-common-utils/ls-having/releases/download/0.0.7/ls-having_0.0.7_Linux_x86_64.tar.gz"
      sha256 "b6ca068110494b4cea2a0ad206f5451059496799f147a0cd888257c0c40ca1d8"

      def install
        bin.install "ls-having"
      end
    end
  end
end
