# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LsHaving < Formula
  desc "A command-line tool for finding directories based on specified flag files and other conditions"
  homepage "https://github.com/handy-common-utils/ls-having"
  version "1.0.7"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/handy-common-utils/ls-having/releases/download/v1.0.7/ls-having_1.0.7_darwin_arm64.tar.gz"
      sha256 "acd7086f61d815f005db3ff2c1caba0893ca53122f42dc29d6f8a0e8b412675b"

      def install
        bin.install "ls-having"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/handy-common-utils/ls-having/releases/download/v1.0.7/ls-having_1.0.7_darwin_amd64.tar.gz"
      sha256 "76c41280c861c8a1a17e67c7c908c9d223050a0dda789fde97dd447176765468"

      def install
        bin.install "ls-having"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/handy-common-utils/ls-having/releases/download/v1.0.7/ls-having_1.0.7_linux_arm64.tar.gz"
      sha256 "6d882ca325790c2e42edf22cd7699d8ea4f4ff44ba14c97fb0bb87c536ef832d"

      def install
        bin.install "ls-having"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/handy-common-utils/ls-having/releases/download/v1.0.7/ls-having_1.0.7_linux_amd64.tar.gz"
      sha256 "da47ab2413c82053a9857269a853b1f4cc41aca08bdf2aa96853e2d0e69bdd20"

      def install
        bin.install "ls-having"
      end
    end
  end
end
