# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LsHaving < Formula
  desc "Command 'ls-having' can list directories having specified flag files and optionally meeting other specified conditions."
  homepage "https://github.com/handy-common-utils/ls-having"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/handy-common-utils/ls-having/releases/download/0.1.0/ls-having_0.1.0_Darwin_x86_64.tar.gz"
      sha256 "e97220ce0ea89d1c165991e550fdff7b5f0a9fb7c866737113d2bb5b60b004bb"

      def install
        bin.install "ls-having"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/handy-common-utils/ls-having/releases/download/0.1.0/ls-having_0.1.0_Darwin_arm64.tar.gz"
      sha256 "669ff01ded1609768b06214bd02a26b3496ccf835422233ba0125d4408ef6710"

      def install
        bin.install "ls-having"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/handy-common-utils/ls-having/releases/download/0.1.0/ls-having_0.1.0_Linux_x86_64.tar.gz"
      sha256 "4ab65325f6f12cca7b88c271cad334525cfed1568dfc91c311dd92dc7cac6031"

      def install
        bin.install "ls-having"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/handy-common-utils/ls-having/releases/download/0.1.0/ls-having_0.1.0_Linux_arm64.tar.gz"
      sha256 "835a21e8b940688d16d1645e397c01db8e7983d76d99fd06966df547e08fd55a"

      def install
        bin.install "ls-having"
      end
    end
  end
end
